default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  port: 5432
  database: blog
  username: postgres
  password: password
