version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-star-wars-backend
    user: dev:dev
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app
      - gems:/.gems
    environment:
      - BASE_HREF=/api
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog

volumes:
  gems:
  pgdata:
