AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Max: 50
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 150
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/MutableConstant:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Naming/VariableNumber:
  EnforcedStyle: snake_case