source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'
#==================================================
# RAILS CORE
#==================================================
gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'postgresql', '~> 1.0'
# gem 'activerecord-postgresql-adapter', '~> 0.0.1'
gem 'pry-byebug', '~> 3.9'
gem 'puma', '~> 5.2'
gem 'bootsnap', '>= 1.1.0', require: false


#==================================================
# BACK-END
#==================================================
# gem 'jwt', '~> 2.2.2'
# gem 'rails-i18n', '~> 5.1.1'

#==================================================
# Development environment
#==================================================
group :development do
  gem 'ruby-debug-ide', '~> 0.7.2'
  gem 'debase', '~> 0.2.4'
  # gem 'rubocop', '~> 1.9.1', require: false
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
